#!/bin/bash
# installation for setting up a debian wheezy env
# must be run as root
apt-get install libcurl4-openssl-dev libmicrohttpd-dev libjsoncpp-dev \
    libargtable2-dev cmake libfltk1.3-dev ant ant-doc ant-contrib \
    ant-contrib-cpptasks g++ doxygen lxterminal git gdb tree tmux
echo "deb http://ppa.launchpad.net/webupd8team/java/ubuntu trusty main" | tee \
    /etc/apt/sources.list.d/webupd8team-java.list
echo "deb-src http://ppa.launchpad.net/webupd8team/java/ubuntu trusty main" | tee\
    -a /etc/apt/sources.list.d/webupd8team-java.list
apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys EEA14886
apt-get update
apt-get install oracle-java8-installer

mkdir ~/git/
cd ~/git/
git clone https://github.com/jabocg/dotfiles

echo "don't forget to set up bash, vim, tmux lxde"
