#!/bin/bash
# script to run several tmux windows for easy access

date=$(date "+%F")
tmux new-session -d -s $date
tmux rename-window -t 0 term
if [ ! $1 == '' ] ; then
    tmux new-window -n devel -c $1
else
    tmux new-window -n devel -c ~/SAIFE/
fi
tmux swap-window -s 1 -t 0
tmux select-window -t 0
tmux attach-session -t $date
